export const API_SYS_TASK_LIST = '/platform/sys/task/list'
export const API_SYS_TASK_CREATE = '/platform/sys/task/create'
export const API_SYS_TASK_GET = '/platform/sys/task/get/'
export const API_SYS_TASK_DELETE = '/platform/sys/task/delete/'
export const API_SYS_TASK_UPDATE = '/platform/sys/task/update'
export const API_SYS_TASK_DISABLED = '/platform/sys/task/disabled'
